#Section to define paths for the pre-processing
# This section will be used by the scripts under pre_processing
pre:
  start_date: 2022060100
  end_date: 2022060200
  fclen: 12
  vfld_path: "/scratch/ms/ie/duuw/vfld_vobs_sample/vfld"
  vobs_path: "/scratch/ms/dk/nhd/vfld_vobs_sample/vobs"
  grb_path: "/scratch/kmw/HARP_WW/GRB_INPUT/ECMWF"   # Directory where grib files are stored
  grb_template: "{YYYY}{MM}{DD}{HH}/nomem_ECMWF_DET_{YYYY}{MM}{DD}+{LDT4}.grb"   # grib-file namings
  grb_orog: "/scratch/kmw/HARP_WW/GRB_INPUT/ECMWF/ECMWF_OROGRAPHY.grb"     # file that contains orography
  vfld_template:  #include one for each model if they are different. 
    - "vfld"
  stat_list: "/home/kmw/harp_ww_env/harpUserScripts/R/include/statlist.csv"
  params:
          #    - S10m
    - T2m
      #    - RH2m
#Section to define paths for the verification
# This section will be used by the scripts under verification
verif:
  by_step: "24h"
  fcst_model:
    - ECMWF_DET
  lead_time: seq(0, 12, 1)
  fcst_type: "det" #det or eps
  grps: "leadtime"
  fcst_path: "/scratch/kmw/HARP_WW/FCTABLE"
  obs_path: "/scratch/ms/dk/nhd/OBSTABLE"
  verif_path: "/scratch/ms/dk/nhd/verif_results"
#Section to define the paths for the output
# This section will be used by the plotting scripts
post:
  plot_output: "/scratch/ms/dk/nhd/plots"
  rds_path: "/scratch/ms/dk/nhd/verif_rds"
#This section if only for the scorecards
scorecards:
  ref_model: EC9 
  fcst_model: nea40h11
  params: 
    - T2m
    - S10m
    - RH2m
    - Pmsl
