#Section to define paths for the pre-processing
# This section will be used by the scripts under pre_processing
shared:
  start_date: 2021010100
  end_date: 2021010212
  
pre:
  fclen: 48
  vfld_path: "/ec/res4/scratch/smcd/harpUserScripts/input/vfld"
  vobs_path: "/ec/res4/scratch/smcd/harpUserScripts/input/vobs"
  vfld_template:  #include one for each model if they are different. 
    - "vfld"
  params:
    - S10m
    - T2m
    - RH2m
#Section to define paths for the verification
# This section will be used by the scripts under verification
verif:
  by_step: "12h"
  fcst_model:
    - testmodel
  lead_time: seq(0, 24, 1)
  fcst_type: "det" #det or eps
  grps: "leadtime"
  fcst_path: "/ec/res4/scratch/smcd/harpUserScripts/output/FCTABLE"
  obs_path: "/ec/res4/scratch/smcd/output/OBSTABLE"
  verif_path: "/ec/res4/scratch/smcd/output/verif_results"
#Section to define the paths for the output
# This section will be used by the plotting scripts
post:
  plot_output: "/ec/res4/scratch/smcd/output/plots"
  rds_path: "/ec/res4/scratch/smcd/verif_rds"
#This section if only for the scorecards
scorecards:
  ref_model: testmodel 
  fcst_model: testmodel
  params: 
    - T2m
    - S10m
    - RH2m
    - Pmsl
